### ISSUE TITLE
Testing integration of pusher in an app.

### ISSUE THREAD

**Issue by alain-andre** [pusher/pusher-http-ruby#100]
Hi there, thanks for this awesome gem. I use pusher to generate notifications to my app and I'd like to test the integration. 

I do this with ActionMailer with `register_interceptor` and `config.action_mailer.delivery_method = :test` in **environments/test.rb** and by catching `ActionMailer::Base.deliveries`. 

Is there an already done way to do my tests and not to send to **pusher.com** ?

**Comment by Tybot204** [comment]
@alain-andre I recommend using this gem: https://github.com/tristandunn/pusher-fake
I use it in my projects and don't have any immediate complaints!

**Comment by vivangkumar** [comment]
Closing this. Feel free to reopen if you're not happy with the suggestion above.
