### ISSUE TITLE
How to get the value from pusher app key

### ISSUE THREAD

**Issue by karthickms** [pusher/pusher-http-ruby#108]
Hi All,

How to get the value from network tab using pusher app key. 
Refer the screen shot

![imageedit_2_2851474635](https://cloud.githubusercontent.com/assets/16956722/18263323/c5ee1ca2-7426-11e6-9e2b-11382dd669b1.png)

Please hands to me

**Comment by vivangkumar** [comment]
@karthickms I realise this reply is very late, but I'm not quite sure I understand what you'd like to do. Could you elaborate?

**Comment by vivangkumar** [comment]
Closing this for now.
