### ISSUE TITLE
BUG: undefined method `from_env'

### ISSUE THREAD

**Issue by garmoshka-mo** [pusher/pusher-http-ruby#110]
```
pusher_client = Pusher::Client.from_env
```

Which is specified in Readme gives:

```
NoMethodError: undefined method `from_env' for Pusher::Client:Class
```

**Comment by vivangkumar** [comment]
@garmoshka-mo I can't seem to reproduce this. I can safely use this method.

Apologies for the late response.

**Comment by garmoshka-mo** [comment]
Ok, found issue core - I had `gem 'pusher-client'` instead of `gem 'pusher'`
