### ISSUE TITLE
Pusher.authenticate raises undocumented exception

### ISSUE THREAD

**Issue by rogeriopvl** [pusher/pusher-http-ruby#111]
According to the documentation, `Pusher.authenticate` does not mention any raised exceptions, but in fact if `socket_id` or `channel_name` are invalid, the method raises `Pusher::Error`.

Should this be added to the docs? or am I missing something?

**Comment by vivangkumar** [comment]
@rogeriopvl It does look like the `Pusher.authenticate` method raises `Pusher::Error`. Docs could certainly be updated to reflect this.
