### ISSUE TITLE
trigger_batch not expose to Pusher delegation

### ISSUE THREAD

**Issue by FLemon** [pusher/pusher-http-ruby#113]
Hi, was trying to use `Pusher.trigger_batch` as your documentation instructed, but got undefined method error

had a looked at your `lib/pusher.rb` file, this method is not delegated.

or did i missed something there?

**Comment by FLemon** [comment]
to add on 
on a project that includes the pusher gem
in the console, calling `Pusher` returns the Pusher module, instead of the `default_client`(which i assume is supposed to be returned, by looking at the test)

now i have to call `Pusher.default_client.trigger_batch`

**Comment by vivangkumar** [comment]
Hi @FLemon 

This has been addressed by a PR: https://github.com/pusher/pusher-http-ruby/pull/109.
However, I have yet to merge it and release a new version. I'm going to do that as soon as I get some free time.

**Comment by FLemon** [comment]
@vivangkumar sorry, didn't know there a PR ready for that, will keep an eye on your release notice

thank you
