### ISSUE TITLE
README describes `Pusher.trigger` but Pusher is a class!

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-http-ruby#133]

**Comment by vivangkumar** [comment]
It is actually legit. The `class << self` idiom is used within the module to define a singleton and expose static methods using `Forwardable`. For example: https://github.com/pusher/pusher-http-ruby/blob/master/lib/pusher.rb#L41 delegates the `Pusher.trigger` call to `default_client` which constructs a `Pusher` instance.

**Comment by jameshfisher** [comment]
Oh right! :vomit: I suppose sadly we can't change that now. We could discourage its use though, by not mentioning it in the README.

**Comment by annzenkina** [comment]
Based on what I understand `Pusher.trigger` is the most convenient way to use for Rails developers since you need to specify Pusher object **once** in the global configuration.

**Comment by jameshfisher** [comment]
Yup, this sounds like an old misunderstanding on my part!
