### ISSUE TITLE
How do you disconnect from the server side?

### ISSUE THREAD

**Issue by tacchistudios-doug** [pusher/pusher-http-ruby#141]
I am currently authenticating a user via an access token which has an expiration. However, I don't can't to see the find disconnect method. I want to disable all broadcasts to Pusher in Rails if the user's access token has expired. How can I do this?

**Comment by annzenkina** [comment]
I’m really sorry for such a delay in getting back to you. Unfortunately, it’s impossible to set the expiration date on the token in the current implementation. We might consider this in the future, but it’s on our roadmap currently. 

This is not an issue in the library, therefore I’m going to close it. I would suggest you reaching out to us at support@pusher.com for the questions about the product in the future.
