### ISSUE TITLE
DEPRECATION WARNING `request#content_type` in Rails v7.0.1

### ISSUE THREAD

**Issue by mpg-tomohiko-mimura** [pusher/pusher-http-ruby#179]
The following deprecated warning will be generated when executing `pusher.webhook(request)` in Rails v7.0.1.

```
DEPRECATION WARNING: Rails 7.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead.
```

This is a warning for a change in Railsv7.1.
ref. https://github.com/rails/rails/commit/840551307139324300b943901d84cbacba11862d

Depending on the value of `CONTENT_TYPE` in the webhook, rails v7.1 will not work properly.

Should we use `request#media_type`?
https://github.com/pusher/pusher-http-ruby/blob/08af7fba7c52f95f9a6d7ac7c6da603fbda80502/lib/pusher/webhook.rb#L37

Let me know what the Pusher development team thinks.

**Comment by mpg-tomohiko-mimura** [comment]
@elverkilde 

What do you think about this issue?

**Comment by yoLotus** [comment]
Hello, is there any update planned for this deprecation?
