### ISSUE TITLE
Pusher::Webhook#event for presence channel missing  `user_info`

### ISSUE THREAD

**Issue by ber8749** [pusher/pusher-http-ruby#184]
The [documentation for presence channels](https://github.com/pusher/pusher-http-ruby#presence-channels) shows that `user_info` can be passed into the `Pusher#authentication` function. I would expect that the corresponding `member_added` or `member_removed` webhook event would contain that same `user_info`, but in my testing so far that has not been the case. Instead, the presence events look something like this:
```
{
  "channel"=>"presence-channel_name", 
  "name"=>"member_added", 
  "user_id"=>"100"
}
```
Am I missing something, or has this information been stripped from the event for some reason?

**Comment by benw-pusher** [comment]
Hi, we don't include the user info details in the webhook payload - as the user_info is generated and owned by your systems we only provide the user_id. With this you can then conduct any lookups or enrichment of the event with the info you hold about the user. This also keeps the payload size to a minimum. 
At this time we don't have any plans to add user_info to the presence event webhooks.
