### ISSUE TITLE
Replace httpclient with a more recent updated http client

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [pusher/pusher-http-ruby#186]
See https://github.com/nahi/httpclient/issues/445

We cannot use the pusher library right now because of this..

**Comment by benjamin-tang-pusher** [comment]
Hi, unfortunately this isn't a Pusher specific issue. You will need to follow the the other commenter's steps to set the path to the local machine's default cert store.

I understand this isn't ideal however, and in the long run if this dependency is no longer maintained, we will move off it.

**Comment by h0jeZvgoxFepBQ2C** [comment]
So you want to continue an absolutely unsecure library? You should at least apply the mentioned fixes to don't have such insecure defaults? Or at least mention in the documenation that this HAS TO BE applied, to stay secure?
