### ISSUE TITLE
Presence authorization relies on side effect of Ruby 1.8 hash to_s

### ISSUE THREAD

**Issue by thechrisoshow** [pusher/pusher-http-ruby#5]
I'm in the middle of writing a presence-auth method for my node.js app, and I had trouble getting it to work using this method: http://pusher.com/docs/auth_signatures.

Looking through this gem, I realise that pusher takes the channel_data hash and converts it to a string using Hash#to_s.  (See here: https://github.com/pusher/pusher-gem/blob/master/lib/pusher/channel.rb#L130 )

This means, that instead of the string_to_sign looking something like:
    "{:user_id=>10, :user_info=>{:name=>\"Mr. Pusher\"}}" 

It instead looks like:
    "user_id10user_infonameMr. Pusher"

This is just a side effect of how 1.8 turns hashes into strings.  (And of course also relies on the ordering of the hash. )  The ramifications are:
1) The presence auth functionality doesn't work in Ruby 1.9
2) Writers of libraries using other languages have to imitate 1.8's strange hash-to-string side effect.

I'd like to fix it, but I realise that the corresponding hashing algorithm within pusher will need to change as well.

**Comment by webreinvent** [comment]
@thechrisoshow  did you get any solution?

**Comment by thechrisoshow** [comment]
@webreinvent I have no idea sorry - that was 6 years ago!
