### ISSUE TITLE
Add specific usage-focussed functions

### ISSUE THREAD

**Issue by hamchapman** [pusher/pusher-http-ruby#69]
The Pusher REST API (https://pusher.com/docs/rest_api) is simple enough that it makes sense to create specific usage-focussed functions for interacting with it.

For example, we could add the following functions:

``` ruby
getOccupiedChannelInfo(info = nil, prefix = nil)

getChannelInfo(channel_name, info = nil)

getPresenceMembers(channel_name)
```

They would essentially only be implemented as utility functions that form the path for you and populate the params, but that still seems like a good idea.

**Comment by zimbatm** [comment]
I don't know at the time of reporting but all of these are covered by the client. Or do you mean add the missing usage direclty in the doc ?
```ruby
pusher.channels({})
pusher.channel_info(channel_name, {})
pusher.channel_users(channel_name, {})
```

**Comment by vivangkumar** [comment]
@hamchapman Can I close this?

**Comment by hamchapman** [comment]
Yeah go for it
