### ISSUE TITLE
when Pusher action 'trigger' returning empty hash ?

### ISSUE THREAD

**Issue by madhusudhan518** [pusher/pusher-http-ruby#74]
when i am trying to  trigger an event , it is returning empty hash instead of true

**Comment by mdpye** [comment]
Hi. Where does it suggest that it will return true?

**Comment by madhusudhan518** [comment]
hi @mdpye  .
i tried before and checked that when it return  true , i am binding that new message using java script.
Pusher['presence-mychannel'].trigger!('new-message', {:from => current_user.name, :subject => @chat_message.content})
after it triggers 
i am wrote javascript
channel.bind('new-message', function(data) {
console.log(data);
});

**Comment by madhusudhan518** [comment]
hi @mdpye .
can you tell me when  pusher trigger return empty hash ?

**Comment by mdpye** [comment]
It returns a hash (currently empty, may in future contain message IDs) on success. On failure an exceptio is thrown.

**Comment by madhusudhan518** [comment]
Thank you @mdpye  . do you know why the 'new-message' event in my channel  not binding .

Pusher['presence-mychannel'].trigger!('new-message', {:from => current_user.name, :subject => @chat_message.content})


channel.bind('new-message', function(data) {
console.log(data);
});

**Comment by mdpye** [comment]
That does look more or less correct to me.

You can see a lot through the Debug Console if you log in to app.pusher.com, for example, you will see your client connect and should see their subscription request, and you can check that each of these is successful and that the channels on publish and subscribe match...

If you still can't work out what is wrong using that then [get in touch with support](https://app.pusher.com/technical-help#problem) who will be glad to help you.
