### ISSUE TITLE
What do you think about removing the "Using multiple Client objects" tests?

### ISSUE THREAD

**Issue by KevinSjoberg** [pusher/pusher-http-ruby#77]
First of all, create work with this library! Really appreciate that you took the effort to support a Ruby-version of the server library. :+1:

While going through the tests in `spec/client_spec.rb` I came to wonder what the tests under "Using multiple Client objects" are actually testing. Since new instances of a Ruby class does not share state, we know that `@client1` and `@client2` will not override each other. Therefor I do not see much value in these tests and suggest we remove them. I'd be happy to create a pull request for it if you share the same opinion.

I may as well overlook something crucial here. If that is the case, I'd love to know more about these tests.

Thanks

**Comment by zimbatm** [comment]
Hey Kevin, thanks for the compliments,

Historically the pusher gem was only using globals. I think these tests were introduced during the transition. Feel free to submit a PR to remove them if they bother you :)

**Comment by KevinSjoberg** [comment]
I see. Makes sense. I think we can safely remove them then since it's leftovers from a previous architecture. Removing code is always a good thing. :+1:

**Comment by zimbatm** [comment]
Ok :)
