### ISSUE TITLE
Excessive logging from HttpClient

### ISSUE THREAD

**Issue by kat3kasper** [pusher/pusher-http-ruby#80]
HttpClient logs a warning `Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.` This is the only gem we're using with a dependency on `httpclient`. We are getting hundreds of logs a minute. 

https://github.com/nahi/httpclient/blob/master/lib/httpclient/cookie.rb

**Comment by zimbatm** [comment]
Hi @kat3kasper, can you patch the library in your development environment to raise an exception at that point and give me the backtrace ? I don't know how to re-produce the issue otherwise since the pusher gem also doesn't use cookies.

**Comment by kat3kasper** [comment]
We found that something else was actually using cookies. Thanks for the help
