### ISSUE TITLE
Signature namespace collision.

### ISSUE THREAD

**Issue by xn** [pusher/pusher-http-ruby#82]
Duplicate of #52 
I can't use this gem because of the namespace collision, so I forked both signature and pusher. Would you like me to open a PR for this update?

Specs are green for both.

My fork: https://github.com/xn/pusher-http-ruby

Thanks.

**Comment by vivangkumar** [comment]
Hi @xn,

We are working on resolving this. We intend to fork the `signature` gem and rename it under the pusher namespace. After which, we'll update the dependency in the library too. I'll ping when it has been done.

Thanks!

**Comment by xn** [comment]
Thanks!

**Comment by vivangkumar** [comment]
Hi @xn, please take a look at the PR here: https://github.com/pusher/pusher-http-ruby/pull/83

We published the pusher-signature gem today and updated the dependency. Once its been reviewed, I'll release a new version. 

This should hopefully resolve issues for you and for other's who may be in the same boat.

Thanks!

**Comment by vivangkumar** [comment]
Hi again, @xn 

I've just released a new version (v0.14.6) of the library and pushed it to ruby gems.
Please do upgrade your version and get back, if you face any issues at all.

Closing this issue as commit https://github.com/pusher/pusher-http-ruby/commit/419787ffb65bc7c2b279dec0bffd7aa6d4d09074 fixes it.

**Comment by xn** [comment]
Thanks, this is really appreciated.
