### ISSUE TITLE
Pusher.authenticate is not a method

### ISSUE THREAD

**Issue by ryanjohns** [pusher/pusher-http-ruby#87]
The latest 0.15.0 says `Pusher.authenticate` was added and is preferred over the old `Pusher['channel'].authenticate` syntax however there is no `authenticate` method defined on the `Pusher` module. There is an instance method `Pusher::Client#authenticate` but this is not the same.

**Comment by jackfranklin** [comment]
@ryanjohns you're absolutely right, my apologies for this.

I've fixed it in this PR https://github.com/pusher/pusher-http-ruby/pull/88 which I will merge when green and push as 0.15.1.

**Comment by ryanjohns** [comment]
@jackfranklin thanks so much!

**Comment by jackfranklin** [comment]
@ryanjohns this has been released on RubyGems as 0.15.1. Thanks for opening the issue and my apologies again for the initial error in the release.

**Comment by ryanjohns** [comment]
No worries. I have confirmed it is working in 0.15.1. Thanks so much for the super fast fix!
