### ISSUE TITLE
Warnings with Ruby 2.3

### ISSUE THREAD

**Issue by claudiob** [pusher/pusher-http-ruby#91]
When version <= 0.15.2 of the pusher gem is used under Ruby 2.3, the following warnings occur:

```
~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:735:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:500:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:788:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:868:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
```

The warning comes from httpclient, and has already been addressed in https://github.com/nahi/httpclient/pull/287

As soon as a new version of the httpclient gem is released, these warnings should disappear.

**Comment by jackfranklin** [comment]
@claudiob perfect, thank you. I'll keep an eye on httpclient and see if we can push a patch release with the dependency upgraded when the new httpclient is released.

**Comment by mlr** [comment]
Looks like this has been released! 🎉https://github.com/nahi/httpclient/commit/85b3fcde9a0378e9a219765b0b79b465162b173f

**Comment by claudiob** [comment]
Cool! No need to release a new version of pusher-http-ruby then, since the requirement is loose enough.
Running `bundle update httpclient` solves the issue.
