### ISSUE TITLE
Authentication docs conflict, are confusing

### ISSUE THREAD

**Issue by randallb** [pusher/pusher-http-ruby#97]
https://pusher.com/docs/authenticating_users - says auth this way

```ruby
class PusherController < ApplicationController

  def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
        :user_id => current_user.id, # => required
        :user_info => { # => optional - for example
          :name => current_user.name,
          :email => current_user.email
        }
      })
      render :json => response
    else
      render :text => "Forbidden", :status => '403'
    end
  end
end

```

Your docs say https://github.com/pusher/pusher-http-ruby#global-deprecated

`Configuring Pusher can also be done globally on the Pusher class. NOTE! This is a deprecated feature and will be removed in future versions of this library!`

So how am I supposed to auth using the new format? It's not immediately clear. Would love clarification / clarity. Going to auth using globals for now.

**Comment by randallb** [comment]
I had an unrelated syntax error that was making me more confused.

The actual way to auth using the new client style w/o globals:

```ruby
response = PUSHER[params[:channel_name]].authenticate(params[:socket_id],{user_id: rand(200000) + 1, user_info: {lol: 'ok'}})
```

I'll make a PR.

**Comment by zimbatm** [comment]
Hey, thanks for the report.

I have removed the deprecation because it's bad to predict the future. If it's going to happen a new major version of the library is going to be released and upgrade instructions will come along.

I also fixed the dashboard example and the doc a little bit. The dashboard examples are also going to go live tomorrow.
